[package]
name = "ownterm-desktop"
version.workspace = true
description = "Desktop local-first para shells locais e SSH."
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "ownterm_desktop"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = "2.6.3"

[dependencies]
ownterm-application = { path = "../../../crates/ownterm-application" }
ownterm-domain = { path = "../../../crates/ownterm-domain" }
ownterm-platform = { path = "../../../crates/ownterm-platform" }
ownterm-storage-sqlite = { path = "../../../crates/ownterm-storage-sqlite" }
ownterm-terminal = { path = "../../../crates/ownterm-terminal" }
serde = { version = "1.0.229", features = ["derive"] }
tauri = "2.11.3"
uuid = { version = "1.26.0", features = ["v4"] }
